security:
    password_hashers:
        App\Security\User: 'auto'

    providers:
        user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|\.well-known)/
            security: false

        auth:
            pattern: ^/(csrf-token|api/login|api/signup|api/health)
            security: false

        api_docs:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator
            entry_point: App\Security\ApiLoginEntryPoint

        main:
            pattern: ^/
            lazy: true
            provider: user_provider
            custom_authenticators:
                - App\Security\SessionAuthenticator
            entry_point: App\Security\LoginEntryPoint
            logout:
                path: app_logout

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/email-verify, roles: PUBLIC_ACCESS }
        - { path: ^/csrf-token, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/signup, roles: PUBLIC_ACCESS }
        - { path: ^/api/health, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_API_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_API_USER, ROLE_USER]
