# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # default locale used by the translator component
    locale: 'en'
    app.encryption_key: '%env(ENCRYPTION_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injected dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Aws\DynamoDb\DynamoDbClient:
        arguments:
            -   region: '%env(AWS_REGION)%'
                version: 'latest'
                endpoint: '%env(default::DYNAMODB_ENDPOINT)%'
                credentials:
                    key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret: '%env(AWS_SECRET_ACCESS_KEY)%'

    App\Security\ApiKeyAuthenticator:
        autowire: true
        autoconfigure: true

    App\Service\ApiKeyService:
        autowire: true
        autoconfigure: true

    App\Repository\CrisisRepository:
        autowire: true
        autoconfigure: true

    App\Controller\ApiKeyController:
        autowire: true
        autoconfigure: true

    App\Controller\CrisisController:
        autowire: true
        autoconfigure: true

    App\Command\GenerateApiKeyCommand:
        autowire: true
        autoconfigure: true

    App\Security\UserProvider:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\ApiDocsAuthController:
        autowire: true
        autoconfigure: true
